# Generated by Django 4.0.4 on 2025-06-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField()),
                ('messages', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_history',
            },
        ),
        migrations.CreateModel(
            name='emodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField()),
                ('ENAME', models.CharField(max_length=20)),
                ('ETYPE', models.CharField(max_length=20)),
                ('EDESC', models.CharField(max_length=20)),
                ('EVIDEO', models.FileField(upload_to='video')),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
        migrations.CreateModel(
            name='ymodel',
            fields=[
                ('YID', models.AutoField(primary_key=True, serialize=False)),
                ('UID', models.IntegerField()),
                ('YNAME', models.CharField(max_length=100)),
                ('YTYPE', models.CharField(max_length=50)),
                ('YDESC', models.CharField(max_length=6000)),
                ('YPIC', models.FileField(upload_to='pictures')),
            ],
            options={
                'db_table': 'yoga',
            },
        ),
    ]
