# Generated by Django 4.0.4 on 2025-07-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_chathistory_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'youtube_video',
            },
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
